### ISSUE TITLE
[FEATURE] Create a hydra plugin for deephypr

### ISSUE THREAD

**Issue by alexk101** [deephyper/deephyper#334]
**Is your feature request related to a problem? Please describe.**
Not a problem, but more of an improvement to certain workflows. Many machine learning and ai project have taken to [hydra](https://hydra.cc) as a reproducible method for generating and sharing configurations. Hydra also supports a [plugin system](https://hydra.cc/docs/plugins/ax_sweeper/) which already has support for optimizers like [optuna](https://optuna.org/), [nevergrad](https://facebookresearch.github.io/nevergrad/), and [ax](https://ax.dev/). It would be nice be able to configure hyperparameter sweeps in the same kind of way that these plugins allow directly within hydra.

**Describe the solution you'd like**
The implementation of a plugin for hydra which will allow for the easy configuration of sweeps with deephypr.

**Describe alternatives you've considered**
The currently workflow is to manually write a deephypr optimization script in python, which is usually project specific and not simple/easy to share.

**Additional context**
There are examples of how these could be approached in all of the plugin pages for each of the ones I listed above. What the optimal approach is would likely be a matter of preference and style/goals of the deephypr project.

**Comment by alexk101** [comment]
The plugin interface that would have to be implemented is defined [here]()https://github.com/facebookresearch/hydra/blob/main/hydra/plugins/sweeper.py. 

Using the ax plugin as an example, the immediate interface is implemented [here](https://github.com/facebookresearch/hydra/blob/main/plugins/hydra_ax_sweeper/hydra_plugins/hydra_ax_sweeper/ax_sweeper.py), while the actual "core" functionality that plugs into ax is [here](https://github.com/facebookresearch/hydra/blob/main/plugins/hydra_ax_sweeper/hydra_plugins/hydra_ax_sweeper/_core.py).

This allows for hyperparameter searches to be defined as follows

```yaml
defaults:
  - override hydra/sweeper: ax

# Banana function
# https://en.wikipedia.org/wiki/Rosenbrock_function
banana:
  # To be minimized
  x: ???
  y: ???

hydra:
  sweeper:
    # The following part of config is used to setup the Hydra Ax plugin and is optional
    ax_config:

      # max_trials is application-specific. Tune it for your use case
      max_trials: 20

      experiment:
        # Default to minimize, set to false to maximize
        minimize: true

      early_stop:
        # Number of epochs without a significant improvement from
        # the currently known best parameters
        # An Epoch is defined as a batch of trials executed in parallel
        max_epochs_without_improvement: 10

      # the synthetic measurements in this example have 0 error
      # which is specified by setting is_noisy to false
      is_noisy: false

      params:
        banana.x:
          type: range
          bounds: [-5, 5]
        banana.y:
          type: range
          bounds: [-5, 10.1]
```

Let me know if that was enough of an example.
